from os import listdir
from os.path import isfile, join, abspath
import pickle
import ujson
from collections import Counter
import random
INDEX_DIC_MITRE_LEVEL2_VECTOR = {
    "Active Scanning": 0,
    "Gather Victim Host Information": 1,
    "Gather Victim Identity Information": 2,
    "Gather Victim Network Information": 3,
    "Gather Victim Org Information": 4,
    "Phishing for Information": 5,
    "Search Closed Sources": 6,
    "Search Open Technical Databases": 7,
    "Search Open Websites/Domains": 8,
    "Search Victim-Owned Websites": 9,
    "Acquire Infrastructure": 10,
    "Compromise Accounts": 11,
    "Compromise Infrastructure": 12,
    "Develop Capabilities": 13,
    "Establish Accounts": 14,
    "Obtain Capabilities": 15,
    "Stage Capabilities": 16,
    "Drive-by Compromise": 17,
    "Exploit Public-Facing Application": 18,
    "External Remote Services": 19,
    "Hardware Additions": 20,
    "Phishing": 21,
    "Replication Through Removable Media": 22,
    "Supply Chain Compromise": 23,
    "Trusted Relationship": 24,
    "Valid Accounts": 25,
    "Command and Scripting Interpreter": 26,
    "Container Administration Command": 27,
    "Deploy Container": 28,
    "Exploitation for Client Execution": 29,
    "Inter-Process Communication": 30,
    "Native API": 31,
    "Scheduled Task/Job": 32,
    "Shared Modules": 33,
    "Software Deployment Tools": 34,
    "System Services": 35,
    "User Execution": 36,
    "Windows Management Instrumentation": 37,
    "Account Manipulation": 38,
    "BITS Jobs": 39,
    "Boot or Logon Autostart Execution": 40,
    "Boot or Logon Initialization Scripts": 41,
    "Browser Extensions": 42,
    "Compromise Client Software Binary": 43,
    "Create Account": 44,
    "Create or Modify System Process": 45,
    "Event Triggered Execution": 46,
    "Hijack Execution Flow": 47,
    "Implant Internal Image": 48,
    "Modify Authentication Process": 49,
    "Office Application Startup": 50,
    "Pre-OS Boot": 51,
    "Server Software Component": 52,
    "Traffic Signaling": 53,
    "Abuse Elevation Control Mechanism": 54,
    "Access Token Manipulation": 55,
    "Domain Policy Modification": 56,
    "Escape to Host": 57,
    "Exploitation for Privilege Escalation": 58,
    "Process Injection": 59,
    "Build Image on Host": 60,
    "Debugger Evasion": 61,
    "Deobfuscate/Decode Files or Information": 62,
    "Direct Volume Access": 63,
    "Execution Guardrails": 64,
    "Exploitation for Defense Evasion": 65,
    "File and Directory Permissions Modification": 66,
    "Hide Artifacts": 67,
    "Impair Defenses": 68,
    "Indicator Removal on Host": 69,
    "Indirect Command Execution": 70,
    "Masquerading": 71,
    "Modify Cloud Compute Infrastructure": 72,
    "Modify Registry": 73,
    "Modify System Image": 74,
    "Network Boundary Bridging": 75,
    "Obfuscated Files or Information": 76,
    "Plist File Modification": 77,
    "Reflective Code Loading": 78,
    "Rogue Domain Controller": 79,
    "Rootkit": 80,
    "Subvert Trust Controls": 81,
    "System Binary Proxy Execution": 82,
    "System Script Proxy Execution": 83,
    "Template Injection": 84,
    "Trusted Developer Utilities Proxy Execution": 85,
    "Unused/Unsupported Cloud Regions": 86,
    "Use Alternate Authentication Material": 87,
    "Virtualization/Sandbox Evasion": 88,
    "Weaken Encryption": 89,
    "XSL Script Processing": 90,
    "Adversary-in-the-Middle": 91,
    "Brute Force": 92,
    "Credentials from Password Stores": 93,
    "Exploitation for Credential Access": 94,
    "Forced Authentication": 95,
    "Forge Web Credentials": 96,
    "Input Capture": 97,
    "Multi-Factor Authentication Interception": 98,
    "Multi-Factor Authentication Request Generation": 99,
    "Network Sniffing": 100,
    "OS Credential Dumping": 101,
    "Steal Application Access Token": 102,
    "Steal or Forge Kerberos Tickets": 103,
    "Steal Web Session Cookie": 104,
    "Unsecured Credentials": 105,
    "Account Discovery": 106,
    "Application Window Discovery": 107,
    "Browser Bookmark Discovery": 108,
    "Cloud Infrastructure Discovery": 109,
    "Cloud Service Dashboard": 110,
    "Cloud Service Discovery": 111,
    "Cloud Storage Object Discovery": 112,
    "Container and Resource Discovery": 113,
    "Domain Trust Discovery": 114,
    "File and Directory Discovery": 115,
    "Group Policy Discovery": 116,
    "Network Service Discovery": 117,
    "Network Share Discovery": 118,
    "Password Policy Discovery": 119,
    "Peripheral Device Discovery": 120,
    "Permission Groups Discovery": 121,
    "Process Discovery": 122,
    "Query Registry": 123,
    "Remote System Discovery": 124,
    "Software Discovery": 125,
    "System Information Discovery": 126,
    "System Location Discovery": 127,
    "System Network Configuration Discovery": 128,
    "System Network Connections Discovery": 129,
    "System Owner/User Discovery": 130,
    "System Service Discovery": 131,
    "System Time Discovery": 132,
    "Exploitation of Remote Services": 133,
    "Internal Spearphishing": 134,
    "Lateral Tool Transfer": 135,
    "Remote Service Session Hijacking": 136,
    "Remote Services": 137,
    "Taint Shared Content": 138,
    "Archive Collected Data": 139,
    "Audio Capture": 140,
    "Automated Collection": 141,
    "Browser Session Hijacking": 142,
    "Clipboard Data": 143,
    "Data from Cloud Storage Object": 144,
    "Data from Configuration Repository": 145,
    "Data from Information Repositories": 146,
    "Data from Local System": 147,
    "Data from Network Shared Drive": 148,
    "Data from Removable Media": 149,
    "Data Staged": 150,
    "Email Collection": 151,
    "Screen Capture": 152,
    "Video Capture": 153,
    "Application Layer Protocol": 154,
    "Communication Through Removable Media": 155,
    "Data Encoding": 156,
    "Data Obfuscation": 157,
    "Dynamic Resolution": 158,
    "Encrypted Channel": 159,
    "Fallback Channels": 160,
    "Ingress Tool Transfer": 161,
    "Multi-Stage Channels": 162,
    "Non-Application Layer Protocol": 163,
    "Non-Standard Port": 164,
    "Protocol Tunneling": 165,
    "Proxy": 166,
    "Remote Access Software": 167,
    "Web Service": 168,
    "Automated Exfiltration": 169,
    "Data Transfer Size Limits": 170,
    "Exfiltration Over Alternative Protocol": 171,
    "Exfiltration Over C2 Channel": 172,
    "Exfiltration Over Other Network Medium": 173,
    "Exfiltration Over Physical Medium": 174,
    "Exfiltration Over Web Service": 175,
    "Scheduled Transfer": 176,
    "Transfer Data to Cloud Account": 177,
    "Account Access Removal": 178,
    "Data Destruction": 179,
    "Data Encrypted for Impact": 180,
    "Data Manipulation": 181,
    "Defacement": 182,
    "Disk Wipe": 183,
    "Endpoint Denial of Service": 184,
    "Firmware Corruption": 185,
    "Inhibit System Recovery": 186,
    "Network Denial of Service": 187,
    "Resource Hijacking": 188,
    "Service Stop": 189,
    "System Shutdown/Reboot": 190,
}

DICT_LEVEL23_TO_LEVEL2 = {
    "Active Scanning": "Active Scanning",
    "Scanning IP Blocks": "Active Scanning",
    "Vulnerability Scanning": "Active Scanning",
    "Wordlist Scanning": "Active Scanning",
    "Gather Victim Host Information": "Gather Victim Host Information",
    "Hardware": "Gather Victim Host Information",
    "Software": "Gather Victim Host Information",
    "Firmware": "Gather Victim Host Information",
    "Client Configurations": "Gather Victim Host Information",
    "Gather Victim Identity Information": "Gather Victim Identity Information",
    "Credentials": "Gather Victim Identity Information",
    "Email Addresses": "Gather Victim Identity Information",
    "Employee Names": "Gather Victim Identity Information",
    "Gather Victim Network Information": "Gather Victim Network Information",
    "Domain Properties": "Gather Victim Network Information",
    "DNS": "Application Layer Protocol",
    "Network Trust Dependencies": "Gather Victim Network Information",
    "Network Topology": "Gather Victim Network Information",
    "IP Addresses": "Gather Victim Network Information",
    "Network Security Appliances": "Gather Victim Network Information",
    "Gather Victim Org Information": "Gather Victim Org Information",
    "Determine Physical Locations": "Gather Victim Org Information",
    "Business Relationships": "Gather Victim Org Information",
    "Identify Business Tempo": "Gather Victim Org Information",
    "Identify Roles": "Gather Victim Org Information",
    "Phishing for Information": "Phishing for Information",
    "Spearphishing Service": "Phishing for Information",
    "Spearphishing Attachment": "Phishing",
    "Spearphishing Link": "Phishing",
    "Search Closed Sources": "Search Closed Sources",
    "Threat Intel Vendors": "Search Closed Sources",
    "Purchase Technical Data": "Search Closed Sources",
    "Search Open Technical Databases": "Search Open Technical Databases",
    "DNS/Passive DNS": "Search Open Technical Databases",
    "WHOIS": "Search Open Technical Databases",
    "Digital Certificates": "Obtain Capabilities",
    "CDNs": "Search Open Technical Databases",
    "Scan Databases": "Search Open Technical Databases",
    "Search Open Websites/Domains": "Search Open Websites/Domains",
    "Social Media": "Search Open Websites/Domains",
    "Search Engines": "Search Open Websites/Domains",
    "Search Victim-Owned Websites": "Search Victim-Owned Websites",
    "Acquire Infrastructure": "Acquire Infrastructure",
    "Domains": "Compromise Infrastructure",
    "DNS Server": "Compromise Infrastructure",
    "Virtual Private Server": "Compromise Infrastructure",
    "Server": "Compromise Infrastructure",
    "Botnet": "Compromise Infrastructure",
    "Web Services": "Compromise Infrastructure",
    "Compromise Accounts": "Compromise Accounts",
    "Social Media Accounts": "Establish Accounts",
    "Email Accounts": "Establish Accounts",
    "Compromise Infrastructure": "Compromise Infrastructure",
    "Develop Capabilities": "Develop Capabilities",
    "Malware": "Obtain Capabilities",
    "Code Signing Certificates": "Obtain Capabilities",
    "Exploits": "Obtain Capabilities",
    "Establish Accounts": "Establish Accounts",
    "Obtain Capabilities": "Obtain Capabilities",
    "Tool": "Obtain Capabilities",
    "Vulnerabilities": "Obtain Capabilities",
    "Stage Capabilities": "Stage Capabilities",
    "Upload Malware": "Stage Capabilities",
    "Upload Tool": "Stage Capabilities",
    "Install Digital Certificate": "Stage Capabilities",
    "Drive-by Target": "Stage Capabilities",
    "Link Target": "Stage Capabilities",
    "Drive-by Compromise": "Drive-by Compromise",
    "Exploit Public-Facing Application": "Exploit Public-Facing Application",
    "External Remote Services": "External Remote Services",
    "Hardware Additions": "Hardware Additions",
    "Phishing": "Phishing",
    "Spearphishing via Service": "Phishing",
    "Replication Through Removable Media": "Replication Through Removable Media",
    "Supply Chain Compromise": "Supply Chain Compromise",
    "Compromise Software Dependencies and Development Tools": "Supply Chain Compromise",
    "Compromise Software Supply Chain": "Supply Chain Compromise",
    "Compromise Hardware Supply Chain": "Supply Chain Compromise",
    "Trusted Relationship": "Trusted Relationship",
    "Valid Accounts": "Valid Accounts",
    "Default Accounts": "Valid Accounts",
    "Domain Accounts": "Valid Accounts",
    "Local Accounts": "Valid Accounts",
    "Cloud Accounts": "Valid Accounts",
    "Command and Scripting Interpreter": "Command and Scripting Interpreter",
    "PowerShell": "Command and Scripting Interpreter",
    "AppleScript": "Command and Scripting Interpreter",
    "Windows Command Shell": "Command and Scripting Interpreter",
    "Unix Shell": "Command and Scripting Interpreter",
    "Visual Basic": "Command and Scripting Interpreter",
    "Python": "Command and Scripting Interpreter",
    "JavaScript": "Command and Scripting Interpreter",
    "Network Device CLI": "Command and Scripting Interpreter",
    "Container Administration Command": "Container Administration Command",
    "Deploy Container": "Deploy Container",
    "Exploitation for Client Execution": "Exploitation for Client Execution",
    "Inter-Process Communication": "Inter-Process Communication",
    "Component Object Model": "Inter-Process Communication",
    "Dynamic Data Exchange": "Inter-Process Communication",
    "XPC Services": "Inter-Process Communication",
    "Native API": "Native API",
    "Scheduled Task/Job": "Scheduled Task/Job",
    "At": "Scheduled Task/Job",
    "Cron": "Scheduled Task/Job",
    "Scheduled Task": "Scheduled Task/Job",
    "Systemd Timers": "Scheduled Task/Job",
    "Container Orchestration Job": "Scheduled Task/Job",
    "Shared Modules": "Shared Modules",
    "Software Deployment Tools": "Software Deployment Tools",
    "System Services": "System Services",
    "Launchctl": "System Services",
    "Service Execution": "System Services",
    "User Execution": "User Execution",
    "Malicious Link": "User Execution",
    "Malicious File": "User Execution",
    "Malicious Image": "User Execution",
    "Windows Management Instrumentation": "Windows Management Instrumentation",
    "Account Manipulation": "Account Manipulation",
    "Additional Cloud Credentials": "Account Manipulation",
    "Additional Email Delegate Permissions": "Account Manipulation",
    "Additional Cloud Roles": "Account Manipulation",
    "SSH Authorized Keys": "Account Manipulation",
    "Device Registration": "Account Manipulation",
    "BITS Jobs": "BITS Jobs",
    "Boot or Logon Autostart Execution": "Boot or Logon Autostart Execution",
    "Registry Run Keys / Startup Folder": "Boot or Logon Autostart Execution",
    "Authentication Package": "Boot or Logon Autostart Execution",
    "Time Providers": "Boot or Logon Autostart Execution",
    "Winlogon Helper DLL": "Boot or Logon Autostart Execution",
    "Security Support Provider": "Boot or Logon Autostart Execution",
    "Kernel Modules and Extensions": "Boot or Logon Autostart Execution",
    "Re-opened Applications": "Boot or Logon Autostart Execution",
    "LSASS Driver": "Boot or Logon Autostart Execution",
    "Shortcut Modification": "Boot or Logon Autostart Execution",
    "Port Monitors": "Boot or Logon Autostart Execution",
    "Print Processors": "Boot or Logon Autostart Execution",
    "XDG Autostart Entries": "Boot or Logon Autostart Execution",
    "Active Setup": "Boot or Logon Autostart Execution",
    "Login Items": "Boot or Logon Autostart Execution",
    "Boot or Logon Initialization Scripts": "Boot or Logon Initialization Scripts",
    "Logon Script (Windows)": "Boot or Logon Initialization Scripts",
    "Login Hook": "Boot or Logon Initialization Scripts",
    "Network Logon Script": "Boot or Logon Initialization Scripts",
    "RC Scripts": "Boot or Logon Initialization Scripts",
    "Startup Items": "Boot or Logon Initialization Scripts",
    "Browser Extensions": "Browser Extensions",
    "Compromise Client Software Binary": "Compromise Client Software Binary",
    "Create Account": "Create Account",
    "Local Account": "Account Discovery",
    "Domain Account": "Account Discovery",
    "Cloud Account": "Account Discovery",
    "Create or Modify System Process": "Create or Modify System Process",
    "Launch Agent": "Create or Modify System Process",
    "Systemd Service": "Create or Modify System Process",
    "Windows Service": "Create or Modify System Process",
    "Launch Daemon": "Create or Modify System Process",
    "Event Triggered Execution": "Event Triggered Execution",
    "Change Default File Association": "Event Triggered Execution",
    "Screensaver": "Event Triggered Execution",
    "Windows Management Instrumentation Event Subscription": "Event Triggered Execution",
    "Unix Shell Configuration Modification": "Event Triggered Execution",
    "Trap": "Event Triggered Execution",
    "LC_LOAD_DYLIB Addition": "Event Triggered Execution",
    "Netsh Helper DLL": "Event Triggered Execution",
    "Accessibility Features": "Event Triggered Execution",
    "AppCert DLLs": "Event Triggered Execution",
    "AppInit DLLs": "Event Triggered Execution",
    "Application Shimming": "Event Triggered Execution",
    "Image File Execution Options Injection": "Event Triggered Execution",
    "PowerShell Profile": "Event Triggered Execution",
    "Emond": "Event Triggered Execution",
    "Component Object Model Hijacking": "Event Triggered Execution",
    "Hijack Execution Flow": "Hijack Execution Flow",
    "DLL Search Order Hijacking": "Hijack Execution Flow",
    "DLL Side-Loading": "Hijack Execution Flow",
    "Dylib Hijacking": "Hijack Execution Flow",
    "Executable Installer File Permissions Weakness": "Hijack Execution Flow",
    "Dynamic Linker Hijacking": "Hijack Execution Flow",
    "Path Interception by PATH Environment Variable": "Hijack Execution Flow",
    "Path Interception by Search Order Hijacking": "Hijack Execution Flow",
    "Path Interception by Unquoted Path": "Hijack Execution Flow",
    "Services File Permissions Weakness": "Hijack Execution Flow",
    "Services Registry Permissions Weakness": "Hijack Execution Flow",
    "COR_PROFILER": "Hijack Execution Flow",
    "KernelCallbackTable": "Hijack Execution Flow",
    "Implant Internal Image": "Implant Internal Image",
    "Modify Authentication Process": "Modify Authentication Process",
    "Domain Controller Authentication": "Modify Authentication Process",
    "Password Filter DLL": "Modify Authentication Process",
    "Pluggable Authentication Modules": "Modify Authentication Process",
    "Network Device Authentication": "Modify Authentication Process",
    "Reversible Encryption": "Modify Authentication Process",
    "Office Application Startup": "Office Application Startup",
    "Office Template Macros": "Office Application Startup",
    "Office Test": "Office Application Startup",
    "Outlook Forms": "Office Application Startup",
    "Outlook Home Page": "Office Application Startup",
    "Outlook Rules": "Office Application Startup",
    "Add-ins": "Office Application Startup",
    "Pre-OS Boot": "Pre-OS Boot",
    "System Firmware": "Pre-OS Boot",
    "Component Firmware": "Pre-OS Boot",
    "Bootkit": "Pre-OS Boot",
    "ROMMONkit": "Pre-OS Boot",
    "TFTP Boot": "Pre-OS Boot",
    "Server Software Component": "Server Software Component",
    "SQL Stored Procedures": "Server Software Component",
    "Transport Agent": "Server Software Component",
    "Web Shell": "Server Software Component",
    "IIS Components": "Server Software Component",
    "Terminal Services DLL": "Server Software Component",
    "Traffic Signaling": "Traffic Signaling",
    "Port Knocking": "Traffic Signaling",
    "Abuse Elevation Control Mechanism": "Abuse Elevation Control Mechanism",
    "Setuid and Setgid": "Abuse Elevation Control Mechanism",
    "Bypass User Account Control": "Abuse Elevation Control Mechanism",
    "Sudo and Sudo Caching": "Abuse Elevation Control Mechanism",
    "Elevated Execution with Prompt": "Abuse Elevation Control Mechanism",
    "Access Token Manipulation": "Access Token Manipulation",
    "Token Impersonation/Theft": "Access Token Manipulation",
    "Create Process with Token": "Access Token Manipulation",
    "Make and Impersonate Token": "Access Token Manipulation",
    "Parent PID Spoofing": "Access Token Manipulation",
    "SID-History Injection": "Access Token Manipulation",
    "": "Domain Policy Modification",
    "Domain Policy Modification": "Domain Policy Modification",
    "Escape to Host": "Escape to Host",
    "Exploitation for Privilege Escalation": "Exploitation for Privilege Escalation",
    "Process Injection": "Process Injection",
    "Dynamic-link Library Injection": "Process Injection",
    "Portable Executable Injection": "Process Injection",
    "Thread Execution Hijacking": "Process Injection",
    "Asynchronous Procedure Call": "Process Injection",
    "Thread Local Storage": "Process Injection",
    "Ptrace System Calls": "Process Injection",
    "Proc Memory": "Process Injection",
    "Extra Window Memory Injection": "Process Injection",
    "Process Hollowing": "Process Injection",
    "Process Doppelgänging": "Process Injection",
    "VDSO Hijacking": "Process Injection",
    "ListPlanting": "Process Injection",
    "Build Image on Host": "Build Image on Host",
    "Debugger Evasion": "Debugger Evasion",
    "Deobfuscate/Decode Files or Information": "Deobfuscate/Decode Files or Information",
    "Direct Volume Access": "Direct Volume Access",
    "Group Policy Modification": "Domain Policy Modification",
    "Domain Trust Modification": "Domain Policy Modification",
    "Execution Guardrails": "Execution Guardrails",
    "Environmental Keying": "Execution Guardrails",
    "Exploitation for Defense Evasion": "Exploitation for Defense Evasion",
    "File and Directory Permissions Modification": "File and Directory Permissions Modification",
    "Windows File and Directory Permissions Modification": "File and Directory Permissions Modification",
    "Linux and Mac File and Directory Permissions Modification": "File and Directory Permissions Modification",
    "Hide Artifacts": "Hide Artifacts",
    "Hidden Files and Directories": "Hide Artifacts",
    "Hidden Users": "Hide Artifacts",
    "Hidden Window": "Hide Artifacts",
    "NTFS File Attributes": "Hide Artifacts",
    "Hidden File System": "Hide Artifacts",
    "Run Virtual Instance": "Hide Artifacts",
    "VBA Stomping": "Hide Artifacts",
    "Email Hiding Rules": "Hide Artifacts",
    "Resource Forking": "Hide Artifacts",
    "Process Argument Spoofing": "Hide Artifacts",
    "COR_PROFILERCOR_PROFILER": "Hijack Execution Flow",
    "Impair Defenses": "Impair Defenses",
    "Disable or Modify Tools": "Impair Defenses",
    "Disable Windows Event Logging": "Impair Defenses",
    "Impair Command History Logging": "Impair Defenses",
    "Disable or Modify System Firewall": "Impair Defenses",
    "Indicator Blocking": "Impair Defenses",
    "Disable or Modify Cloud Firewall": "Impair Defenses",
    "Disable Cloud Logs": "Impair Defenses",
    "Safe Mode Boot": "Impair Defenses",
    "Downgrade Attack": "Impair Defenses",
    "Indicator Removal on Host": "Indicator Removal on Host",
    "Clear Windows Event Logs": "Indicator Removal on Host",
    "Clear Linux or Mac System Logs": "Indicator Removal on Host",
    "Clear Command History": "Indicator Removal on Host",
    "File Deletion": "Indicator Removal on Host",
    "Network Share Connection Removal": "Indicator Removal on Host",
    "Timestomp": "Indicator Removal on Host",
    "Indirect Command Execution": "Indirect Command Execution",
    "Masquerading": "Masquerading",
    "Invalid Code Signature": "Masquerading",
    "Right-to-Left Override": "Masquerading",
    "Rename System Utilities": "Masquerading",
    "Masquerade Task or Service": "Masquerading",
    "Match Legitimate Name or Location": "Masquerading",
    "Space after Filename": "Masquerading",
    "Double File Extension": "Masquerading",
    "Modify Cloud Compute Infrastructure": "Modify Cloud Compute Infrastructure",
    "Create Snapshot": "Modify Cloud Compute Infrastructure",
    "Create Cloud Instance": "Modify Cloud Compute Infrastructure",
    "Delete Cloud Instance": "Modify Cloud Compute Infrastructure",
    "Revert Cloud Instance": "Modify Cloud Compute Infrastructure",
    "Modify Registry": "Modify Registry",
    "Modify System Image": "Modify System Image",
    "Patch System Image": "Modify System Image",
    "Downgrade System Image": "Modify System Image",
    "Network Boundary Bridging": "Network Boundary Bridging",
    "Network Address Translation Traversal": "Network Boundary Bridging",
    "Obfuscated Files or Information": "Obfuscated Files or Information",
    "Binary Padding": "Obfuscated Files or Information",
    "Software Packing": "Obfuscated Files or Information",
    "Steganography": "Data Obfuscation",
    "Compile After Delivery": "Obfuscated Files or Information",
    "Indicator Removal from Tools": "Obfuscated Files or Information",
    "HTML Smuggling": "Obfuscated Files or Information",
    "Plist File Modification": "Plist File Modification",
    "Reflective Code Loading": "Reflective Code Loading",
    "Rogue Domain Controller": "Rogue Domain Controller",
    "Rootkit": "Rootkit",
    "Subvert Trust Controls": "Subvert Trust Controls",
    "Gatekeeper Bypass": "Subvert Trust Controls",
    "Code Signing": "Subvert Trust Controls",
    "SIP and Trust Provider Hijacking": "Subvert Trust Controls",
    "Install Root Certificate": "Subvert Trust Controls",
    "Mark-of-the-Web Bypass": "Subvert Trust Controls",
    "Code Signing Policy Modification": "Subvert Trust Controls",
    "System Binary Proxy Execution": "System Binary Proxy Execution",
    "Compiled HTML File": "System Binary Proxy Execution",
    "Control Panel": "System Binary Proxy Execution",
    "CMSTP": "System Binary Proxy Execution",
    "InstallUtil": "System Binary Proxy Execution",
    "Mshta": "System Binary Proxy Execution",
    "Msiexec": "System Binary Proxy Execution",
    "Odbcconf": "System Binary Proxy Execution",
    "Regsvcs/Regasm": "System Binary Proxy Execution",
    "Regsvr32": "System Binary Proxy Execution",
    "Rundll32": "System Binary Proxy Execution",
    "Verclsid": "System Binary Proxy Execution",
    "Mavinject": "System Binary Proxy Execution",
    "MMC": "System Binary Proxy Execution",
    "System Script Proxy Execution": "System Script Proxy Execution",
    "PubPrn": "System Script Proxy Execution",
    "Template Injection": "Template Injection",
    "Trusted Developer Utilities Proxy Execution": "Trusted Developer Utilities Proxy Execution",
    "MSBuild": "Trusted Developer Utilities Proxy Execution",
    "Unused/Unsupported Cloud Regions": "Unused/Unsupported Cloud Regions",
    "Use Alternate Authentication Material": "Use Alternate Authentication Material",
    "Application Access Token": "Use Alternate Authentication Material",
    "Pass the Hash": "Use Alternate Authentication Material",
    "Pass the Ticket": "Use Alternate Authentication Material",
    "Web Session Cookie": "Use Alternate Authentication Material",
    "Virtualization/Sandbox Evasion": "Virtualization/Sandbox Evasion",
    "System Checks": "Virtualization/Sandbox Evasion",
    "User Activity Based Checks": "Virtualization/Sandbox Evasion",
    "Time Based Evasion": "Virtualization/Sandbox Evasion",
    "Weaken Encryption": "Weaken Encryption",
    "Reduce Key Space": "Weaken Encryption",
    "Disable Crypto Hardware": "Weaken Encryption",
    "XSL Script Processing": "XSL Script Processing",
    "Adversary-in-the-Middle": "Adversary-in-the-Middle",
    "LLMNR/NBT-NS Poisoning and SMB Relay": "Adversary-in-the-Middle",
    "ARP Cache Poisoning": "Adversary-in-the-Middle",
    "DHCP Spoofing": "Adversary-in-the-Middle",
    "Brute Force": "Brute Force",
    "Password Guessing": "Brute Force",
    "Password Cracking": "Brute Force",
    "Password Spraying": "Brute Force",
    "Credential Stuffing": "Brute Force",
    "Credentials from Password Stores": "Credentials from Password Stores",
    "Keychain": "Credentials from Password Stores",
    "Securityd Memory": "Credentials from Password Stores",
    "Credentials from Web Browsers": "Credentials from Password Stores",
    "Windows Credential Manager": "Credentials from Password Stores",
    "Password Managers": "Credentials from Password Stores",
    "Exploitation for Credential Access": "Exploitation for Credential Access",
    "Forced Authentication": "Forced Authentication",
    "Forge Web Credentials": "Forge Web Credentials",
    "Web Cookies": "Forge Web Credentials",
    "SAML Tokens": "Forge Web Credentials",
    "Input Capture": "Input Capture",
    "Keylogging": "Input Capture",
    "GUI Input Capture": "Input Capture",
    "Web Portal Capture": "Input Capture",
    "Credential API Hooking": "Input Capture",
    "Multi-Factor Authentication Interception": "Multi-Factor Authentication Interception",
    "Multi-Factor Authentication Request Generation": "Multi-Factor Authentication Request Generation",
    "Network Sniffing": "Network Sniffing",
    "OS Credential Dumping": "OS Credential Dumping",
    "LSASS Memory": "OS Credential Dumping",
    "Security Account Manager": "OS Credential Dumping",
    "NTDS": "OS Credential Dumping",
    "LSA Secrets": "OS Credential Dumping",
    "Cached Domain Credentials": "OS Credential Dumping",
    "DCSync": "OS Credential Dumping",
    "Proc Filesystem": "OS Credential Dumping",
    "/etc/passwd and /etc/shadow": "OS Credential Dumping",
    "Steal Application Access Token": "Steal Application Access Token",
    "Steal or Forge Kerberos Tickets": "Steal or Forge Kerberos Tickets",
    "Golden Ticket": "Steal or Forge Kerberos Tickets",
    "Silver Ticket": "Steal or Forge Kerberos Tickets",
    "Kerberoasting": "Steal or Forge Kerberos Tickets",
    "AS-REP Roasting": "Steal or Forge Kerberos Tickets",
    "Steal Web Session Cookie": "Steal Web Session Cookie",
    "Unsecured Credentials": "Unsecured Credentials",
    "Credentials In Files": "Unsecured Credentials",
    "Credentials in Registry": "Unsecured Credentials",
    "Bash History": "Unsecured Credentials",
    "Private Keys": "Unsecured Credentials",
    "Cloud Instance Metadata API": "Unsecured Credentials",
    "Group Policy Preferences": "Unsecured Credentials",
    "Container API": "Unsecured Credentials",
    "Account Discovery": "Account Discovery",
    "Email Account": "Account Discovery",
    "Application Window Discovery": "Application Window Discovery",
    "Browser Bookmark Discovery": "Browser Bookmark Discovery",
    "Cloud Infrastructure Discovery": "Cloud Infrastructure Discovery",
    "Cloud Service Dashboard": "Cloud Service Dashboard",
    "Cloud Service Discovery": "Cloud Service Discovery",
    "Cloud Storage Object Discovery": "Cloud Storage Object Discovery",
    "Container and Resource Discovery": "Container and Resource Discovery",
    "Domain Trust Discovery": "Domain Trust Discovery",
    "File and Directory Discovery": "File and Directory Discovery",
    "Group Policy Discovery": "Group Policy Discovery",
    "Network Service Discovery": "Network Service Discovery",
    "Network Share Discovery": "Network Share Discovery",
    "Password Policy Discovery": "Password Policy Discovery",
    "Peripheral Device Discovery": "Peripheral Device Discovery",
    "Permission Groups Discovery": "Permission Groups Discovery",
    "Local Groups": "Permission Groups Discovery",
    "Domain Groups": "Permission Groups Discovery",
    "Cloud Groups": "Permission Groups Discovery",
    "Process Discovery": "Process Discovery",
    "Query Registry": "Query Registry",
    "Remote System Discovery": "Remote System Discovery",
    "Software Discovery": "Software Discovery",
    "Security Software Discovery": "Software Discovery",
    "System Information Discovery": "System Information Discovery",
    "System Location Discovery": "System Location Discovery",
    "System Language Discovery": "System Location Discovery",
    "System Network Configuration Discovery": "System Network Configuration Discovery",
    "Internet Connection Discovery": "System Network Configuration Discovery",
    "System Network Connections Discovery": "System Network Connections Discovery",
    "System Owner/User Discovery": "System Owner/User Discovery",
    "System Service Discovery": "System Service Discovery",
    "System Time Discovery": "System Time Discovery",
    "Exploitation of Remote Services": "Exploitation of Remote Services",
    "Internal Spearphishing": "Internal Spearphishing",
    "Lateral Tool Transfer": "Lateral Tool Transfer",
    "Remote Service Session Hijacking": "Remote Service Session Hijacking",
    "SSH Hijacking": "Remote Service Session Hijacking",
    "RDP Hijacking": "Remote Service Session Hijacking",
    "Remote Services": "Remote Services",
    "Remote Desktop Protocol": "Remote Services",
    "SMB/Windows Admin Shares": "Remote Services",
    "Distributed Component Object Model": "Remote Services",
    "SSH": "Remote Services",
    "VNC": "Remote Services",
    "Windows Remote Management": "Remote Services",
    "Taint Shared Content": "Taint Shared Content",
    "Archive Collected Data": "Archive Collected Data",
    "Archive via Utility": "Archive Collected Data",
    "Archive via Library": "Archive Collected Data",
    "Archive via Custom Method": "Archive Collected Data",
    "Audio Capture": "Audio Capture",
    "Automated Collection": "Automated Collection",
    "Browser Session Hijacking": "Browser Session Hijacking",
    "Clipboard Data": "Clipboard Data",
    "Data from Cloud Storage Object": "Data from Cloud Storage Object",
    "Data from Configuration Repository": "Data from Configuration Repository",
    "SNMP (MIB Dump)": "Data from Configuration Repository",
    "Network Device Configuration Dump": "Data from Configuration Repository",
    "Data from Information Repositories": "Data from Information Repositories",
    "Confluence": "Data from Information Repositories",
    "Sharepoint": "Data from Information Repositories",
    "Code Repositories": "Data from Information Repositories",
    "Data from Local System": "Data from Local System",
    "Data from Network Shared Drive": "Data from Network Shared Drive",
    "Data from Removable Media": "Data from Removable Media",
    "Data Staged": "Data Staged",
    "Local Data Staging": "Data Staged",
    "Remote Data Staging": "Data Staged",
    "Email Collection": "Email Collection",
    "Local Email Collection": "Email Collection",
    "Remote Email Collection": "Email Collection",
    "Email Forwarding Rule": "Email Collection",
    "Screen Capture": "Screen Capture",
    "Video Capture": "Video Capture",
    "Application Layer Protocol": "Application Layer Protocol",
    "Web Protocols": "Application Layer Protocol",
    "File Transfer Protocols": "Application Layer Protocol",
    "Mail Protocols": "Application Layer Protocol",
    "Communication Through Removable Media": "Communication Through Removable Media",
    "Data Encoding": "Data Encoding",
    "Standard Encoding": "Data Encoding",
    "Non-Standard Encoding": "Data Encoding",
    "Data Obfuscation": "Data Obfuscation",
    "Junk Data": "Data Obfuscation",
    "Protocol Impersonation": "Data Obfuscation",
    "Dynamic Resolution": "Dynamic Resolution",
    "Fast Flux DNS": "Dynamic Resolution",
    "Domain Generation Algorithms": "Dynamic Resolution",
    "DNS Calculation": "Dynamic Resolution",
    "Encrypted Channel": "Encrypted Channel",
    "Symmetric Cryptography": "Encrypted Channel",
    "Asymmetric Cryptography": "Encrypted Channel",
    "Fallback Channels": "Fallback Channels",
    "Ingress Tool Transfer": "Ingress Tool Transfer",
    "Multi-Stage Channels": "Multi-Stage Channels",
    "Non-Application Layer Protocol": "Non-Application Layer Protocol",
    "Non-Standard Port": "Non-Standard Port",
    "Protocol Tunneling": "Protocol Tunneling",
    "Proxy": "Proxy",
    "Internal Proxy": "Proxy",
    "External Proxy": "Proxy",
    "Multi-hop Proxy": "Proxy",
    "Domain Fronting": "Proxy",
    "Remote Access Software": "Remote Access Software",
    "Web Service": "Web Service",
    "Dead Drop Resolver": "Web Service",
    "Bidirectional Communication": "Web Service",
    "One-Way Communication": "Web Service",
    "Automated Exfiltration": "Automated Exfiltration",
    "Traffic Duplication": "Automated Exfiltration",
    "Data Transfer Size Limits": "Data Transfer Size Limits",
    "Exfiltration Over Alternative Protocol": "Exfiltration Over Alternative Protocol",
    "Exfiltration Over Symmetric Encrypted Non-C2 Protocol": "Exfiltration Over Alternative Protocol",
    "Exfiltration Over Asymmetric Encrypted Non-C2 Protocol": "Exfiltration Over Alternative Protocol",
    "Exfiltration Over Unencrypted Non-C2 Protocol": "Exfiltration Over Alternative Protocol",
    "Exfiltration Over C2 Channel": "Exfiltration Over C2 Channel",
    "Exfiltration Over Other Network Medium": "Exfiltration Over Other Network Medium",
    "Exfiltration Over Bluetooth": "Exfiltration Over Other Network Medium",
    "Exfiltration Over Physical Medium": "Exfiltration Over Physical Medium",
    "Exfiltration over USB": "Exfiltration Over Physical Medium",
    "Exfiltration Over Web Service": "Exfiltration Over Web Service",
    "Exfiltration to Code Repository": "Exfiltration Over Web Service",
    "Exfiltration to Cloud Storage": "Exfiltration Over Web Service",
    "Scheduled Transfer": "Scheduled Transfer",
    "Transfer Data to Cloud Account": "Transfer Data to Cloud Account",
    "Account Access Removal": "Account Access Removal",
    "Data Destruction": "Data Destruction",
    "Data Encrypted for Impact": "Data Encrypted for Impact",
    "Data Manipulation": "Data Manipulation",
    "Stored Data Manipulation": "Data Manipulation",
    "Transmitted Data Manipulation": "Data Manipulation",
    "Runtime Data Manipulation": "Data Manipulation",
    "Defacement": "Defacement",
    "Internal Defacement": "Defacement",
    "External Defacement": "Defacement",
    "Disk Wipe": "Disk Wipe",
    "Disk Content Wipe": "Disk Wipe",
    "Disk Structure Wipe": "Disk Wipe",
    "Endpoint Denial of Service": "Endpoint Denial of Service",
    "OS Exhaustion Flood": "Endpoint Denial of Service",
    "Service Exhaustion Flood": "Endpoint Denial of Service",
    "Application Exhaustion Flood": "Endpoint Denial of Service",
    "Application or System Exploitation": "Endpoint Denial of Service",
    "Firmware Corruption": "Firmware Corruption",
    "Inhibit System Recovery": "Inhibit System Recovery",
    "Network Denial of Service": "Network Denial of Service",
    "Direct Network Flood": "Network Denial of Service",
    "Reflection Amplification": "Network Denial of Service",
    "Resource Hijacking": "Resource Hijacking",
    "Service Stop": "Service Stop",
    "System Shutdown/Reboot": "System Shutdown/Reboot",
    "Scripting": "Command and Scripting Interpreter"
}

MITRE_LEVEL2_VECTOR= [
    "Active Scanning",
    "Gather Victim Host Information",
    "Gather Victim Identity Information",
    "Gather Victim Network Information",
    "Gather Victim Org Information",
    "Phishing for Information",
    "Search Closed Sources",
    "Search Open Technical Databases",
    "Search Open Websites/Domains",
    "Search Victim-Owned Websites",
    "Acquire Infrastructure",
    "Compromise Accounts",
    "Compromise Infrastructure",
    "Develop Capabilities",
    "Establish Accounts",
    "Obtain Capabilities",
    "Stage Capabilities",
    "Drive-by Compromise",
    "Exploit Public-Facing Application",
    "External Remote Services",
    "Hardware Additions",
    "Phishing",
    "Replication Through Removable Media",
    "Supply Chain Compromise",
    "Trusted Relationship",
    "Valid Accounts",
    "Command and Scripting Interpreter",
    "Container Administration Command",
    "Deploy Container",
    "Exploitation for Client Execution",
    "Inter-Process Communication",
    "Native API",
    "Scheduled Task/Job",
    "Shared Modules",
    "Software Deployment Tools",
    "System Services",
    "User Execution",
    "Windows Management Instrumentation",
    "Account Manipulation",
    "BITS Jobs",
    "Boot or Logon Autostart Execution",
    "Boot or Logon Initialization Scripts",
    "Browser Extensions",
    "Compromise Client Software Binary",
    "Create Account",
    "Create or Modify System Process",
    "Event Triggered Execution",
    "Hijack Execution Flow",
    "Implant Internal Image",
    "Modify Authentication Process",
    "Office Application Startup",
    "Pre-OS Boot",
    "Server Software Component",
    "Traffic Signaling",
    "Abuse Elevation Control Mechanism",
    "Access Token Manipulation",
    "Domain Policy Modification",
    "Escape to Host",
    "Exploitation for Privilege Escalation",
    "Process Injection",
    "Build Image on Host",
    "Debugger Evasion",
    "Deobfuscate/Decode Files or Information",
    "Direct Volume Access",
    "Execution Guardrails",
    "Exploitation for Defense Evasion",
    "File and Directory Permissions Modification",
    "Hide Artifacts",
    "Impair Defenses",
    "Indicator Removal on Host",
    "Indirect Command Execution",
    "Masquerading",
    "Modify Cloud Compute Infrastructure",
    "Modify Registry",
    "Modify System Image",
    "Network Boundary Bridging",
    "Obfuscated Files or Information",
    "Plist File Modification",
    "Reflective Code Loading",
    "Rogue Domain Controller",
    "Rootkit",
    "Subvert Trust Controls",
    "System Binary Proxy Execution",
    "System Script Proxy Execution",
    "Template Injection",
    "Trusted Developer Utilities Proxy Execution",
    "Unused/Unsupported Cloud Regions",
    "Use Alternate Authentication Material",
    "Virtualization/Sandbox Evasion",
    "Weaken Encryption",
    "XSL Script Processing",
    "Adversary-in-the-Middle",
    "Brute Force",
    "Credentials from Password Stores",
    "Exploitation for Credential Access",
    "Forced Authentication",
    "Forge Web Credentials",
    "Input Capture",
    "Multi-Factor Authentication Interception",
    "Multi-Factor Authentication Request Generation",
    "Network Sniffing",
    "OS Credential Dumping",
    "Steal Application Access Token",
    "Steal or Forge Kerberos Tickets",
    "Steal Web Session Cookie",
    "Unsecured Credentials",
    "Account Discovery",
    "Application Window Discovery",
    "Browser Bookmark Discovery",
    "Cloud Infrastructure Discovery",
    "Cloud Service Dashboard",
    "Cloud Service Discovery",
    "Cloud Storage Object Discovery",
    "Container and Resource Discovery",
    "Domain Trust Discovery",
    "File and Directory Discovery",
    "Group Policy Discovery",
    "Network Service Discovery",
    "Network Share Discovery",
    "Password Policy Discovery",
    "Peripheral Device Discovery",
    "Permission Groups Discovery",
    "Process Discovery",
    "Query Registry",
    "Remote System Discovery",
    "Software Discovery",
    "System Information Discovery",
    "System Location Discovery",
    "System Network Configuration Discovery",
    "System Network Connections Discovery",
    "System Owner/User Discovery",
    "System Service Discovery",
    "System Time Discovery",
    "Exploitation of Remote Services",
    "Internal Spearphishing",
    "Lateral Tool Transfer",
    "Remote Service Session Hijacking",
    "Remote Services",
    "Taint Shared Content",
    "Archive Collected Data",
    "Audio Capture",
    "Automated Collection",
    "Browser Session Hijacking",
    "Clipboard Data",
    "Data from Cloud Storage Object",
    "Data from Configuration Repository",
    "Data from Information Repositories",
    "Data from Local System",
    "Data from Network Shared Drive",
    "Data from Removable Media",
    "Data Staged",
    "Email Collection",
    "Screen Capture",
    "Video Capture",
    "Application Layer Protocol",
    "Communication Through Removable Media",
    "Data Encoding",
    "Data Obfuscation",
    "Dynamic Resolution",
    "Encrypted Channel",
    "Fallback Channels",
    "Ingress Tool Transfer",
    "Multi-Stage Channels",
    "Non-Application Layer Protocol",
    "Non-Standard Port",
    "Protocol Tunneling",
    "Proxy",
    "Remote Access Software",
    "Web Service",
    "Automated Exfiltration",
    "Data Transfer Size Limits",
    "Exfiltration Over Alternative Protocol",
    "Exfiltration Over C2 Channel",
    "Exfiltration Over Other Network Medium",
    "Exfiltration Over Physical Medium",
    "Exfiltration Over Web Service",
    "Scheduled Transfer",
    "Transfer Data to Cloud Account",
    "Account Access Removal",
    "Data Destruction",
    "Data Encrypted for Impact",
    "Data Manipulation",
    "Defacement",
    "Disk Wipe",
    "Endpoint Denial of Service",
    "Firmware Corruption",
    "Inhibit System Recovery",
    "Network Denial of Service",
    "Resource Hijacking",
    "Service Stop",
    "System Shutdown/Reboot",
]
print("\n\n============== START ============\n\n")
# 1. Load data
Malwares_info = []
list_Malwares_info = []
path_data = "D:/LEARN/LEARN/DATN/02_resources/mist/"
path_save = "D:/LEARN/LEARN/DATN/02_resources/data_train/"

#load mitre files
false_tag = []
list_MIST_name = listdir(path_data)
print(list_MIST_name[2])
total = 0
MIST_BAG = [[], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], []]
#print(MIST_BAG)

random.shuffle(list_MIST_name)
for i , name in enumerate(list_MIST_name[0:15000]):
    print(f"{i} :  {name}" )
    #print(path_data + name + "-mitre.json")
    f = open(path_data + name)
    data = ujson.load(f)
    f.close()

    for key in data.keys(): 
        try:
            if(len(data[key])>0):
                #print(f"index = {INDEX_DIC_MITRE_LEVEL2_VECTOR[DICT_LEVEL23_TO_LEVEL2[key]]}")
                for data_key in data[key]:
                    data_temp = " ".join(data_key.split(" ")[0:4])
                    MIST_BAG[INDEX_DIC_MITRE_LEVEL2_VECTOR[DICT_LEVEL23_TO_LEVEL2[key]]] += [data_temp]
                # get to ARG3

                #print( len(data[key]))
                total += len(data[key])
            #print(len(data[key]))
        except:
            if(len(data[key])>0):
                false_tag.append(key)


print(len(MIST_BAG[3]))
print(total)
#with open(path_save + '01_malware_to_vectorlv2_listtype.pkl', 'wb') as f:
#    pickle.dump(list_Malwares_info, f)
print(f"FALSE TAG : {Counter(false_tag)}")

match_tag = dict()
unmatch_tag = []
print("\n ====================\n BAG : ")
for i,bag in enumerate(MIST_BAG):
    print(f"{len(bag)} - {MITRE_LEVEL2_VECTOR[i]}" )
    if len(bag) == 0 :
        unmatch_tag.append(MITRE_LEVEL2_VECTOR[i])
    if len(bag) > 0:
        match_tag[MITRE_LEVEL2_VECTOR[i]] = len(bag)

print(f"unmatch : {len(unmatch_tag)}")
print(f"match : {len(match_tag)}")
print(match_tag)

with open(path_save + 'behavior_bag_raw.pkl', 'wb') as f:
    pickle.dump(MIST_BAG, f)

with open(path_save + 'behavior_bag_raw.pkl', 'rb') as f:
    behavior_bag = pickle.load(f)

flatten_list = lambda y:[x for a in y for x in flatten_list(a)] if type(y) is list else [y]
behavior_bag = flatten_list(behavior_bag)
print(len(behavior_bag))
behavior_bag = list(set(behavior_bag))
print(f"final bag : {len(behavior_bag)}")

with open(f"{path_save}behavior_bag_2arg_{len(match_tag)}_{len(behavior_bag)}.pkl", 'wb') as f:
    pickle.dump(behavior_bag, f)

with open(f"{path_save}match_tag_2arg_{len(match_tag)}_{len(behavior_bag)}.pkl", 'wb') as f:
    pickle.dump(match_tag, f)