from os import listdir
from os.path import isfile, join, abspath
import pickle
from re import template
import ujson
from collections import Counter

dict_level2_to_level1 = {
    "Active Scanning": ["Reconnaissance"],
    "Gather Victim Host Information": ["Reconnaissance"],
    "Gather Victim Identity Information": ["Reconnaissance"],
    "Gather Victim Network Information": ["Reconnaissance"],
    "Gather Victim Org Information": ["Reconnaissance"],
    "Phishing for Information": ["Reconnaissance"],
    "Search Closed Sources": ["Reconnaissance"],
    "Search Open Technical Databases": ["Reconnaissance"],
    "Search Open Websites/Domains": ["Reconnaissance"],
    "Search Victim-Owned Websites": ["Reconnaissance"],
    "Acquire Infrastructure": ["Resource Development"],
    "Compromise Accounts": ["Resource Development"],
    "Compromise Infrastructure": ["Resource Development"],
    "Develop Capabilities": ["Resource Development"],
    "Establish Accounts": ["Resource Development"],
    "Obtain Capabilities": ["Resource Development"],
    "Stage Capabilities": ["Resource Development"],
    "Drive-by Compromise": ["initial-access"],
    "Exploit Public-Facing Application": ["initial-access"],
    "External Remote Services": ["initial-access", "persistence"],
    "Hardware Additions": ["initial-access"],
    "Phishing": ["initial-access"],
    "Replication Through Removable Media": ["initial-access", "lateral-movement"],
    "Supply Chain Compromise": ["initial-access"],
    "Trusted Relationship": ["initial-access"],
    "Valid Accounts": [
        "initial-access",
        "persistence",
        "privilege-escalation",
        "defense-evasion",
    ],
    "Command and Scripting Interpreter": ["execution"],
    "Container Administration Command": ["execution"],
    "Deploy Container": ["execution", "defense-evasion"],
    "Exploitation for Client Execution": ["execution"],
    "Inter-Process Communication": ["execution"],
    "Native API": ["execution"],
    "Scheduled Task/Job": ["execution", "persistence", "privilege-escalation"],
    "Shared Modules": ["execution"],
    "Software Deployment Tools": ["execution", "lateral-movement"],
    "System Services": ["execution"],
    "User Execution": ["execution"],
    "Windows Management Instrumentation": ["execution"],
    "Account Manipulation": ["persistence"],
    "BITS Jobs": ["persistence", "defense-evasion"],
    "Boot or Logon Autostart Execution": ["persistence", "privilege-escalation"],
    "Boot or Logon Initialization Scripts": ["persistence", "privilege-escalation"],
    "Browser Extensions": ["persistence"],
    "Compromise Client Software Binary": ["persistence"],
    "Create Account": ["persistence"],
    "Create or Modify System Process": ["persistence", "privilege-escalation"],
    "Event Triggered Execution": ["persistence", "privilege-escalation"],
    "Hijack Execution Flow": ["persistence", "privilege-escalation", "defense-evasion"],
    "Implant Internal Image": ["persistence"],
    "Modify Authentication Process": [
        "persistence",
        "defense-evasion",
        "credential-access",
    ],
    "Office Application Startup": ["persistence"],
    "Pre-OS Boot": ["persistence", "defense-evasion"],
    "Server Software Component": ["persistence"],
    "Traffic Signaling": ["persistence", "defense-evasion", "command-and-control"],
    "Abuse Elevation Control Mechanism": ["privilege-escalation", "defense-evasion"],
    "Access Token Manipulation": ["privilege-escalation", "defense-evasion"],
    "Domain Policy Modification": ["privilege-escalation", "defense-evasion"],
    "Escape to Host": ["privilege-escalation"],
    "Exploitation for Privilege Escalation": ["privilege-escalation"],
    "Process Injection": ["privilege-escalation", "defense-evasion"],
    "Build Image on Host": ["defense-evasion"],
    "Debugger Evasion": ["defense-evasion", "discovery"],
    "Deobfuscate/Decode Files or Information": ["defense-evasion"],
    "Direct Volume Access": ["defense-evasion"],
    "Execution Guardrails": ["defense-evasion"],
    "Exploitation for Defense Evasion": ["defense-evasion"],
    "File and Directory Permissions Modification": ["defense-evasion"],
    "Hide Artifacts": ["defense-evasion"],
    "Impair Defenses": ["defense-evasion"],
    "Indicator Removal on Host": ["defense-evasion"],
    "Indirect Command Execution": ["defense-evasion"],
    "Masquerading": ["defense-evasion"],
    "Modify Cloud Compute Infrastructure": ["defense-evasion"],
    "Modify Registry": ["defense-evasion"],
    "Modify System Image": ["defense-evasion"],
    "Network Boundary Bridging": ["defense-evasion"],
    "Obfuscated Files or Information": ["defense-evasion"],
    "Plist File Modification": ["defense-evasion"],
    "Reflective Code Loading": ["defense-evasion"],
    "Rogue Domain Controller": ["defense-evasion"],
    "Rootkit": ["defense-evasion"],
    "Subvert Trust Controls": ["defense-evasion"],
    "System Binary Proxy Execution": ["defense-evasion"],
    "System Script Proxy Execution": ["defense-evasion"],
    "Template Injection": ["defense-evasion"],
    "Trusted Developer Utilities Proxy Execution": ["defense-evasion"],
    "Unused/Unsupported Cloud Regions": ["defense-evasion"],
    "Use Alternate Authentication Material": ["defense-evasion", "lateral-movement"],
    "Virtualization/Sandbox Evasion": ["defense-evasion", "discovery"],
    "Weaken Encryption": ["defense-evasion"],
    "XSL Script Processing": ["defense-evasion"],
    "Adversary-in-the-Middle": ["credential-access", "collection"],
    "Brute Force": ["credential-access"],
    "Credentials from Password Stores": ["credential-access"],
    "Exploitation for Credential Access": ["credential-access"],
    "Forced Authentication": ["credential-access"],
    "Forge Web Credentials": ["credential-access"],
    "Input Capture": ["credential-access", "collection"],
    "Multi-Factor Authentication Interception": ["credential-access"],
    "Multi-Factor Authentication Request Generation": ["credential-access"],
    "Network Sniffing": ["credential-access", "discovery"],
    "OS Credential Dumping": ["credential-access"],
    "Steal Application Access Token": ["credential-access"],
    "Steal or Forge Kerberos Tickets": ["credential-access"],
    "Steal Web Session Cookie": ["credential-access"],
    "Unsecured Credentials": ["credential-access"],
    "Account Discovery": ["discovery"],
    "Application Window Discovery": ["discovery"],
    "Browser Bookmark Discovery": ["discovery"],
    "Cloud Infrastructure Discovery": ["discovery"],
    "Cloud Service Dashboard": ["discovery"],
    "Cloud Service Discovery": ["discovery"],
    "Cloud Storage Object Discovery": ["discovery"],
    "Container and Resource Discovery": ["discovery"],
    "Domain Trust Discovery": ["discovery"],
    "File and Directory Discovery": ["discovery"],
    "Group Policy Discovery": ["discovery"],
    "Network Service Discovery": ["discovery"],
    "Network Share Discovery": ["discovery"],
    "Password Policy Discovery": ["discovery"],
    "Peripheral Device Discovery": ["discovery"],
    "Permission Groups Discovery": ["discovery"],
    "Process Discovery": ["discovery"],
    "Query Registry": ["discovery"],
    "Remote System Discovery": ["discovery"],
    "Software Discovery": ["discovery"],
    "System Information Discovery": ["discovery"],
    "System Location Discovery": ["discovery"],
    "System Network Configuration Discovery": ["discovery"],
    "System Network Connections Discovery": ["discovery"],
    "System Owner/User Discovery": ["discovery"],
    "System Service Discovery": ["discovery"],
    "System Time Discovery": ["discovery"],
    "Exploitation of Remote Services": ["lateral-movement"],
    "Internal Spearphishing": ["lateral-movement"],
    "Lateral Tool Transfer": ["lateral-movement"],
    "Remote Service Session Hijacking": ["lateral-movement"],
    "Remote Services": ["lateral-movement"],
    "Taint Shared Content": ["lateral-movement"],
    "Archive Collected Data": ["collection"],
    "Audio Capture": ["collection"],
    "Automated Collection": ["collection"],
    "Browser Session Hijacking": ["collection"],
    "Clipboard Data": ["collection"],
    "Data from Cloud Storage Object": ["collection"],
    "Data from Configuration Repository": ["collection"],
    "Data from Information Repositories": ["collection"],
    "Data from Local System": ["collection"],
    "Data from Network Shared Drive": ["collection"],
    "Data from Removable Media": ["collection"],
    "Data Staged": ["collection"],
    "Email Collection": ["collection"],
    "Screen Capture": ["collection"],
    "Video Capture": ["collection"],
    "Application Layer Protocol": ["command-and-control"],
    "Communication Through Removable Media": ["command-and-control"],
    "Data Encoding": ["command-and-control"],
    "Data Obfuscation": ["command-and-control"],
    "Dynamic Resolution": ["command-and-control"],
    "Encrypted Channel": ["command-and-control"],
    "Fallback Channels": ["command-and-control"],
    "Ingress Tool Transfer": ["command-and-control"],
    "Multi-Stage Channels": ["command-and-control"],
    "Non-Application Layer Protocol": ["command-and-control"],
    "Non-Standard Port": ["command-and-control"],
    "Protocol Tunneling": ["command-and-control"],
    "Proxy": ["command-and-control"],
    "Remote Access Software": ["command-and-control"],
    "Web Service": ["command-and-control"],
    "Automated Exfiltration": ["exfiltration"],
    "Data Transfer Size Limits": ["exfiltration"],
    "Exfiltration Over Alternative Protocol": ["exfiltration"],
    "Exfiltration Over C2 Channel": ["exfiltration"],
    "Exfiltration Over Other Network Medium": ["exfiltration"],
    "Exfiltration Over Physical Medium": ["exfiltration"],
    "Exfiltration Over Web Service": ["exfiltration"],
    "Scheduled Transfer": ["exfiltration"],
    "Transfer Data to Cloud Account": ["exfiltration"],
    "Account Access Removal": ["impact"],
    "Data Destruction": ["impact"],
    "Data Encrypted for Impact": ["impact"],
    "Data Manipulation": ["impact"],
    "Defacement": ["impact"],
    "Disk Wipe": ["impact"],
    "Endpoint Denial of Service": ["impact"],
    "Firmware Corruption": ["impact"],
    "Inhibit System Recovery": ["impact"],
    "Network Denial of Service": ["impact"],
    "Resource Hijacking": ["impact"],
    "Service Stop": ["impact"],
    "System Shutdown/Reboot": ["impact"],
}

dict_level2_to_id = {
    "Active Scanning": "T1595",
    "Gather Victim Host Information": "T1592",
    "Gather Victim Identity Information": "T1589",
    "Gather Victim Network Information": "T1590",
    "Gather Victim Org Information": "T1591",
    "Phishing for Information": "T1598",
    "Search Closed Sources": "T1597",
    "Search Open Technical Databases": "T1596",
    "Search Open Websites/Domains": "T1593",
    "Search Victim-Owned Websites": "T1594",
    "Acquire Infrastructure": "T1583",
    "Compromise Accounts": "T1586",
    "Compromise Infrastructure": "T1584",
    "Develop Capabilities": "T1587",
    "Establish Accounts": "T1585",
    "Obtain Capabilities": "T1588",
    "Stage Capabilities": "T1608",
    "Drive-by Compromise": "T1189",
    "Exploit Public-Facing Application": "T1190",
    "External Remote Services": "T1133",
    "Hardware Additions": "T1200",
    "Phishing": "T1566",
    "Replication Through Removable Media": "T1091",
    "Supply Chain Compromise": "T1195",
    "Trusted Relationship": "T1199",
    "Valid Accounts": "T1078",
    "Command and Scripting Interpreter": "T1059",
    "Container Administration Command": "T1609",
    "Deploy Container": "T1610",
    "Exploitation for Client Execution": "T1203",
    "Inter-Process Communication": "T1559",
    "Native API": "T1106",
    "Scheduled Task/Job": "T1053",
    "Shared Modules": "T1129",
    "Software Deployment Tools": "T1072",
    "System Services": "T1569",
    "User Execution": "T1204",
    "Windows Management Instrumentation": "T1047",
    "Account Manipulation": "T1098",
    "BITS Jobs": "T1197",
    "Boot or Logon Autostart Execution": "T1547",
    "Boot or Logon Initialization Scripts": "T1037",
    "Browser Extensions": "T1176",
    "Compromise Client Software Binary": "T1554",
    "Create Account": "T1136",
    "Create or Modify System Process": "T1543",
    "Event Triggered Execution": "T1546",
    "Hijack Execution Flow": "T1574",
    "Implant Internal Image": "T1525",
    "Modify Authentication Process": "T1556",
    "Office Application Startup": "T1137",
    "Pre-OS Boot": "T1542",
    "Server Software Component": "T1505",
    "Traffic Signaling": "T1205",
    "Abuse Elevation Control Mechanism": "T1548",
    "Access Token Manipulation": "T1134",
    "Domain Policy Modification": "T1484",
    "Escape to Host": "T1611",
    "Exploitation for Privilege Escalation": "T1068",
    "Process Injection": "T1055",
    "Build Image on Host": "T1612",
    "Debugger Evasion": "T1622",
    "Deobfuscate/Decode Files or Information": "T1140",
    "Direct Volume Access": "T1006",
    "Execution Guardrails": "T1480",
    "Exploitation for Defense Evasion": "T1211",
    "File and Directory Permissions Modification": "T1222",
    "Hide Artifacts": "T1564",
    "Impair Defenses": "T1562",
    "Indicator Removal on Host": "T1070",
    "Indirect Command Execution": "T1202",
    "Masquerading": "T1036",
    "Modify Cloud Compute Infrastructure": "T1578",
    "Modify Registry": "T1112",
    "Modify System Image": "T1601",
    "Network Boundary Bridging": "T1599",
    "Obfuscated Files or Information": "T1027",
    "Plist File Modification": "T1647",
    "Reflective Code Loading": "T1620",
    "Rogue Domain Controller": "T1207",
    "Rootkit": "T1014",
    "Subvert Trust Controls": "T1553",
    "System Binary Proxy Execution": "T1218",
    "System Script Proxy Execution": "T1216",
    "Template Injection": "T1221",
    "Trusted Developer Utilities Proxy Execution": "T1127",
    "Unused/Unsupported Cloud Regions": "T1535",
    "Use Alternate Authentication Material": "T1550",
    "Virtualization/Sandbox Evasion": "T1497",
    "Weaken Encryption": "T1600",
    "XSL Script Processing": "T1220",
    "Adversary-in-the-Middle": "T1557",
    "Brute Force": "T1110",
    "Credentials from Password Stores": "T1555",
    "Exploitation for Credential Access": "T1212",
    "Forced Authentication": "T1187",
    "Forge Web Credentials": "T1606",
    "Input Capture": "T1056",
    "Multi-Factor Authentication Interception": "T1111",
    "Multi-Factor Authentication Request Generation": "T1621",
    "Network Sniffing": "T1040",
    "OS Credential Dumping": "T1003",
    "Steal Application Access Token": "T1528",
    "Steal or Forge Kerberos Tickets": "T1558",
    "Steal Web Session Cookie": "T1539",
    "Unsecured Credentials": "T1552",
    "Account Discovery": "T1087",
    "Application Window Discovery": "T1010",
    "Browser Bookmark Discovery": "T1217",
    "Cloud Infrastructure Discovery": "T1580",
    "Cloud Service Dashboard": "T1538",
    "Cloud Service Discovery": "T1526",
    "Cloud Storage Object Discovery": "T1619",
    "Container and Resource Discovery": "T1613",
    "Domain Trust Discovery": "T1482",
    "File and Directory Discovery": "T1083",
    "Group Policy Discovery": "T1615",
    "Network Service Discovery": "T1046",
    "Network Share Discovery": "T1135",
    "Password Policy Discovery": "T1201",
    "Peripheral Device Discovery": "T1120",
    "Permission Groups Discovery": "T1069",
    "Process Discovery": "T1057",
    "Query Registry": "T1012",
    "Remote System Discovery": "T1018",
    "Software Discovery": "T1518",
    "System Information Discovery": "T1082",
    "System Location Discovery": "T1614",
    "System Network Configuration Discovery": "T1016",
    "System Network Connections Discovery": "T1049",
    "System Owner/User Discovery": "T1033",
    "System Service Discovery": "T1007",
    "System Time Discovery": "T1124",
    "Exploitation of Remote Services": "T1210",
    "Internal Spearphishing": "T1534",
    "Lateral Tool Transfer": "T1570",
    "Remote Service Session Hijacking": "T1563",
    "Remote Services": "T1021",
    "Taint Shared Content": "T1080",
    "Archive Collected Data": "T1560",
    "Audio Capture": "T1123",
    "Automated Collection": "T1119",
    "Browser Session Hijacking": "T1185",
    "Clipboard Data": "T1115",
    "Data from Cloud Storage Object": "T1530",
    "Data from Configuration Repository": "T1602",
    "Data from Information Repositories": "T1213",
    "Data from Local System": "T1005",
    "Data from Network Shared Drive": "T1039",
    "Data from Removable Media": "T1025",
    "Data Staged": "T1074",
    "Email Collection": "T1114",
    "Screen Capture": "T1113",
    "Video Capture": "T1125",
    "Application Layer Protocol": "T1071",
    "Communication Through Removable Media": "T1092",
    "Data Encoding": "T1132",
    "Data Obfuscation": "T1001",
    "Dynamic Resolution": "T1568",
    "Encrypted Channel": "T1573",
    "Fallback Channels": "T1008",
    "Ingress Tool Transfer": "T1105",
    "Multi-Stage Channels": "T1104",
    "Non-Application Layer Protocol": "T1095",
    "Non-Standard Port": "T1571",
    "Protocol Tunneling": "T1572",
    "Proxy": "T1090",
    "Remote Access Software": "T1219",
    "Web Service": "T1102",
    "Automated Exfiltration": "T1020",
    "Data Transfer Size Limits": "T1030",
    "Exfiltration Over Alternative Protocol": "T1048",
    "Exfiltration Over C2 Channel": "T1041",
    "Exfiltration Over Other Network Medium": "T1011",
    "Exfiltration Over Physical Medium": "T1052",
    "Exfiltration Over Web Service": "T1567",
    "Scheduled Transfer": "T1029",
    "Transfer Data to Cloud Account": "T1537",
    "Account Access Removal": "T1531",
    "Data Destruction": "T1485",
    "Data Encrypted for Impact": "T1486",
    "Data Manipulation": "T1565",
    "Defacement": "T1491",
    "Disk Wipe": "T1561",
    "Endpoint Denial of Service": "T1499",
    "Firmware Corruption": "T1495",
    "Inhibit System Recovery": "T1490",
    "Network Denial of Service": "T1498",
    "Resource Hijacking": "T1496",
    "Service Stop": "T1489",
    "System Shutdown/Reboot": "T1529",
}

MITRE_LEVEL2_VECTOR= [
    "Active Scanning",
    "Gather Victim Host Information",
    "Gather Victim Identity Information",
    "Gather Victim Network Information",
    "Gather Victim Org Information",
    "Phishing for Information",
    "Search Closed Sources",
    "Search Open Technical Databases",
    "Search Open Websites/Domains",
    "Search Victim-Owned Websites",
    "Acquire Infrastructure",
    "Compromise Accounts",
    "Compromise Infrastructure",
    "Develop Capabilities",
    "Establish Accounts",
    "Obtain Capabilities",
    "Stage Capabilities",
    "Drive-by Compromise",
    "Exploit Public-Facing Application",
    "External Remote Services",
    "Hardware Additions",
    "Phishing",
    "Replication Through Removable Media",
    "Supply Chain Compromise",
    "Trusted Relationship",
    "Valid Accounts",
    "Command and Scripting Interpreter",
    "Container Administration Command",
    "Deploy Container",
    "Exploitation for Client Execution",
    "Inter-Process Communication",
    "Native API",
    "Scheduled Task/Job",
    "Shared Modules",
    "Software Deployment Tools",
    "System Services",
    "User Execution",
    "Windows Management Instrumentation",
    "Account Manipulation",
    "BITS Jobs",
    "Boot or Logon Autostart Execution",
    "Boot or Logon Initialization Scripts",
    "Browser Extensions",
    "Compromise Client Software Binary",
    "Create Account",
    "Create or Modify System Process",
    "Event Triggered Execution",
    "Hijack Execution Flow",
    "Implant Internal Image",
    "Modify Authentication Process",
    "Office Application Startup",
    "Pre-OS Boot",
    "Server Software Component",
    "Traffic Signaling",
    "Abuse Elevation Control Mechanism",
    "Access Token Manipulation",
    "Domain Policy Modification",
    "Escape to Host",
    "Exploitation for Privilege Escalation",
    "Process Injection",
    "Build Image on Host",
    "Debugger Evasion",
    "Deobfuscate/Decode Files or Information",
    "Direct Volume Access",
    "Execution Guardrails",
    "Exploitation for Defense Evasion",
    "File and Directory Permissions Modification",
    "Hide Artifacts",
    "Impair Defenses",
    "Indicator Removal on Host",
    "Indirect Command Execution",
    "Masquerading",
    "Modify Cloud Compute Infrastructure",
    "Modify Registry",
    "Modify System Image",
    "Network Boundary Bridging",
    "Obfuscated Files or Information",
    "Plist File Modification",
    "Reflective Code Loading",
    "Rogue Domain Controller",
    "Rootkit",
    "Subvert Trust Controls",
    "System Binary Proxy Execution",
    "System Script Proxy Execution",
    "Template Injection",
    "Trusted Developer Utilities Proxy Execution",
    "Unused/Unsupported Cloud Regions",
    "Use Alternate Authentication Material",
    "Virtualization/Sandbox Evasion",
    "Weaken Encryption",
    "XSL Script Processing",
    "Adversary-in-the-Middle",
    "Brute Force",
    "Credentials from Password Stores",
    "Exploitation for Credential Access",
    "Forced Authentication",
    "Forge Web Credentials",
    "Input Capture",
    "Multi-Factor Authentication Interception",
    "Multi-Factor Authentication Request Generation",
    "Network Sniffing",
    "OS Credential Dumping",
    "Steal Application Access Token",
    "Steal or Forge Kerberos Tickets",
    "Steal Web Session Cookie",
    "Unsecured Credentials",
    "Account Discovery",
    "Application Window Discovery",
    "Browser Bookmark Discovery",
    "Cloud Infrastructure Discovery",
    "Cloud Service Dashboard",
    "Cloud Service Discovery",
    "Cloud Storage Object Discovery",
    "Container and Resource Discovery",
    "Domain Trust Discovery",
    "File and Directory Discovery",
    "Group Policy Discovery",
    "Network Service Discovery",
    "Network Share Discovery",
    "Password Policy Discovery",
    "Peripheral Device Discovery",
    "Permission Groups Discovery",
    "Process Discovery",
    "Query Registry",
    "Remote System Discovery",
    "Software Discovery",
    "System Information Discovery",
    "System Location Discovery",
    "System Network Configuration Discovery",
    "System Network Connections Discovery",
    "System Owner/User Discovery",
    "System Service Discovery",
    "System Time Discovery",
    "Exploitation of Remote Services",
    "Internal Spearphishing",
    "Lateral Tool Transfer",
    "Remote Service Session Hijacking",
    "Remote Services",
    "Taint Shared Content",
    "Archive Collected Data",
    "Audio Capture",
    "Automated Collection",
    "Browser Session Hijacking",
    "Clipboard Data",
    "Data from Cloud Storage Object",
    "Data from Configuration Repository",
    "Data from Information Repositories",
    "Data from Local System",
    "Data from Network Shared Drive",
    "Data from Removable Media",
    "Data Staged",
    "Email Collection",
    "Screen Capture",
    "Video Capture",
    "Application Layer Protocol",
    "Communication Through Removable Media",
    "Data Encoding",
    "Data Obfuscation",
    "Dynamic Resolution",
    "Encrypted Channel",
    "Fallback Channels",
    "Ingress Tool Transfer",
    "Multi-Stage Channels",
    "Non-Application Layer Protocol",
    "Non-Standard Port",
    "Protocol Tunneling",
    "Proxy",
    "Remote Access Software",
    "Web Service",
    "Automated Exfiltration",
    "Data Transfer Size Limits",
    "Exfiltration Over Alternative Protocol",
    "Exfiltration Over C2 Channel",
    "Exfiltration Over Other Network Medium",
    "Exfiltration Over Physical Medium",
    "Exfiltration Over Web Service",
    "Scheduled Transfer",
    "Transfer Data to Cloud Account",
    "Account Access Removal",
    "Data Destruction",
    "Data Encrypted for Impact",
    "Data Manipulation",
    "Defacement",
    "Disk Wipe",
    "Endpoint Denial of Service",
    "Firmware Corruption",
    "Inhibit System Recovery",
    "Network Denial of Service",
    "Resource Hijacking",
    "Service Stop",
    "System Shutdown/Reboot",
]

true = True
false =False
def get_template_MITRE_full():
	template_MITRE_full = {
	"name": "layer",
	"versions": {
		"attack": "11",
		"navigator": "4.6.5",
		"layer": "4.3"
	},
	"domain": "enterprise-attack",
	"description": "",
	"filters": {
		"platforms": [
			"Windows"
		]
	},
	"sorting": 3,
	"layout": {
		"layout": "side",
		"aggregateFunction": "average",
		"showID": true,
		"showName": true,
		"showAggregateScores": false,
		"countUnscored": false
	},
	"hideDisabled": false,
	"techniques": [
		{
			"techniqueID": {
				"Active Scanning": "T1595",
				"Gather Victim Host Information": "T1592",
				"Gather Victim Identity Information": "T1589",
				"Gather Victim Network Information": "T1590",
				"Gather Victim Org Information": "T1591",
				"Phishing for Information": "T1598",
				"Search Closed Sources": "T1597",
				"Search Open Technical Databases": "T1596",
				"Search Open Websites/Domains": "T1593",
				"Search Victim-Owned Websites": "T1594",
				"Acquire Infrastructure": "T1583",
				"Compromise Accounts": "T1586",
				"Compromise Infrastructure": "T1584",
				"Develop Capabilities": "T1587",
				"Establish Accounts": "T1585",
				"Obtain Capabilities": "T1588",
				"Stage Capabilities": "T1608",
				"Drive-by Compromise": "T1189",
				"Exploit Public-Facing Application": "T1190",
				"External Remote Services": "T1133",
				"Hardware Additions": "T1200",
				"Phishing": "T1566",
				"Replication Through Removable Media": "T1091",
				"Supply Chain Compromise": "T1195",
				"Trusted Relationship": "T1199",
				"Valid Accounts": "T1078",
				"Command and Scripting Interpreter": "T1059",
				"Container Administration Command": "T1609",
				"Deploy Container": "T1610",
				"Exploitation for Client Execution": "T1203",
				"Inter-Process Communication": "T1559",
				"Native API": "T1106",
				"Scheduled Task/Job": "T1053",
				"Shared Modules": "T1129",
				"Software Deployment Tools": "T1072",
				"System Services": "T1569",
				"User Execution": "T1204",
				"Windows Management Instrumentation": "T1047",
				"Account Manipulation": "T1098",
				"BITS Jobs": "T1197",
				"Boot or Logon Autostart Execution": "T1547",
				"Boot or Logon Initialization Scripts": "T1037",
				"Browser Extensions": "T1176",
				"Compromise Client Software Binary": "T1554",
				"Create Account": "T1136",
				"Create or Modify System Process": "T1543",
				"Event Triggered Execution": "T1546",
				"Hijack Execution Flow": "T1574",
				"Implant Internal Image": "T1525",
				"Modify Authentication Process": "T1556",
				"Office Application Startup": "T1137",
				"Pre-OS Boot": "T1542",
				"Server Software Component": "T1505",
				"Traffic Signaling": "T1205",
				"Abuse Elevation Control Mechanism": "T1548",
				"Access Token Manipulation": "T1134",
				"Domain Policy Modification": "T1484",
				"Escape to Host": "T1611",
				"Exploitation for Privilege Escalation": "T1068",
				"Process Injection": "T1055",
				"Build Image on Host": "T1612",
				"Debugger Evasion": "T1622",
				"Deobfuscate/Decode Files or Information": "T1140",
				"Direct Volume Access": "T1006",
				"Execution Guardrails": "T1480",
				"Exploitation for Defense Evasion": "T1211",
				"File and Directory Permissions Modification": "T1222",
				"Hide Artifacts": "T1564",
				"Impair Defenses": "T1562",
				"Indicator Removal on Host": "T1070",
				"Indirect Command Execution": "T1202",
				"Masquerading": "T1036",
				"Modify Cloud Compute Infrastructure": "T1578",
				"Modify Registry": "T1112",
				"Modify System Image": "T1601",
				"Network Boundary Bridging": "T1599",
				"Obfuscated Files or Information": "T1027",
				"Plist File Modification": "T1647",
				"Reflective Code Loading": "T1620",
				"Rogue Domain Controller": "T1207",
				"Rootkit": "T1014",
				"Subvert Trust Controls": "T1553",
				"System Binary Proxy Execution": "T1218",
				"System Script Proxy Execution": "T1216",
				"Template Injection": "T1221",
				"Trusted Developer Utilities Proxy Execution": "T1127",
				"Unused/Unsupported Cloud Regions": "T1535",
				"Use Alternate Authentication Material": "T1550",
				"Virtualization/Sandbox Evasion": "T1497",
				"Weaken Encryption": "T1600",
				"XSL Script Processing": "T1220",
				"Adversary-in-the-Middle": "T1557",
				"Brute Force": "T1110",
				"Credentials from Password Stores": "T1555",
				"Exploitation for Credential Access": "T1212",
				"Forced Authentication": "T1187",
				"Forge Web Credentials": "T1606",
				"Input Capture": "T1056",
				"Multi-Factor Authentication Interception": "T1111",
				"Multi-Factor Authentication Request Generation": "T1621",
				"Network Sniffing": "T1040",
				"OS Credential Dumping": "T1003",
				"Steal Application Access Token": "T1528",
				"Steal or Forge Kerberos Tickets": "T1558",
				"Steal Web Session Cookie": "T1539",
				"Unsecured Credentials": "T1552",
				"Account Discovery": "T1087",
				"Application Window Discovery": "T1010",
				"Browser Bookmark Discovery": "T1217",
				"Cloud Infrastructure Discovery": "T1580",
				"Cloud Service Dashboard": "T1538",
				"Cloud Service Discovery": "T1526",
				"Cloud Storage Object Discovery": "T1619",
				"Container and Resource Discovery": "T1613",
				"Domain Trust Discovery": "T1482",
				"File and Directory Discovery": "T1083",
				"Group Policy Discovery": "T1615",
				"Network Service Discovery": "T1046",
				"Network Share Discovery": "T1135",
				"Password Policy Discovery": "T1201",
				"Peripheral Device Discovery": "T1120",
				"Permission Groups Discovery": "T1069",
				"Process Discovery": "T1057",
				"Query Registry": "T1012",
				"Remote System Discovery": "T1018",
				"Software Discovery": "T1518",
				"System Information Discovery": "T1082",
				"System Location Discovery": "T1614",
				"System Network Configuration Discovery": "T1016",
				"System Network Connections Discovery": "T1049",
				"System Owner/User Discovery": "T1033",
				"System Service Discovery": "T1007",
				"System Time Discovery": "T1124",
				"Exploitation of Remote Services": "T1210",
				"Internal Spearphishing": "T1534",
				"Lateral Tool Transfer": "T1570",
				"Remote Service Session Hijacking": "T1563",
				"Remote Services": "T1021",
				"Taint Shared Content": "T1080",
				"Archive Collected Data": "T1560",
				"Audio Capture": "T1123",
				"Automated Collection": "T1119",
				"Browser Session Hijacking": "T1185",
				"Clipboard Data": "T1115",
				"Data from Cloud Storage Object": "T1530",
				"Data from Configuration Repository": "T1602",
				"Data from Information Repositories": "T1213",
				"Data from Local System": "T1005",
				"Data from Network Shared Drive": "T1039",
				"Data from Removable Media": "T1025",
				"Data Staged": "T1074",
				"Email Collection": "T1114",
				"Screen Capture": "T1113",
				"Video Capture": "T1125",
				"Application Layer Protocol": "T1071",
				"Communication Through Removable Media": "T1092",
				"Data Encoding": "T1132",
				"Data Obfuscation": "T1001",
				"Dynamic Resolution": "T1568",
				"Encrypted Channel": "T1573",
				"Fallback Channels": "T1008",
				"Ingress Tool Transfer": "T1105",
				"Multi-Stage Channels": "T1104",
				"Non-Application Layer Protocol": "T1095",
				"Non-Standard Port": "T1571",
				"Protocol Tunneling": "T1572",
				"Proxy": "T1090",
				"Remote Access Software": "T1219",
				"Web Service": "T1102",
				"Automated Exfiltration": "T1020",
				"Data Transfer Size Limits": "T1030",
				"Exfiltration Over Alternative Protocol": "T1048",
				"Exfiltration Over C2 Channel": "T1041",
				"Exfiltration Over Other Network Medium": "T1011",
				"Exfiltration Over Physical Medium": "T1052",
				"Exfiltration Over Web Service": "T1567",
				"Scheduled Transfer": "T1029",
				"Transfer Data to Cloud Account": "T1537",
				"Account Access Removal": "T1531",
				"Data Destruction": "T1485",
				"Data Encrypted for Impact": "T1486",
				"Data Manipulation": "T1565",
				"Defacement": "T1491",
				"Disk Wipe": "T1561",
				"Endpoint Denial of Service": "T1499",
				"Firmware Corruption": "T1495",
				"Inhibit System Recovery": "T1490",
				"Network Denial of Service": "T1498",
				"Resource Hijacking": "T1496",
				"Service Stop": "T1489",
				"System Shutdown/Reboot": "T1529"
			},
			"tactic": "command-and-control",
			"color": "#dadaeb",
			"comment": "",
			"enabled": true,
			"metadata": [],
			"links": [],
			"showSubtechniques": false
		}
	],
	"gradient": {
		"colors": [
			"#ff6666ff",
			"#ffe766ff",
			"#8ec843ff"
		],
		"minValue": 0,
		"maxValue": 100
	},
	"legendItems": [],
	"metadata": [],
	"links": [],
	"showTacticRowBackground": false,
	"tacticRowBackground": "#dddddd",
	"selectTechniquesAcrossTactics": false,
	"selectSubtechniquesWithParent": false
}
	return template_MITRE_full

def get_template_MITRE_small():
	template_MITRE_small = {
	"name": "layer",
	"versions": {
		"attack": "11",
		"navigator": "4.6.5",
		"layer": "4.3"
	},
	"domain": "enterprise-attack",
	"description": "",
	"filters": {
		"platforms": [
			"Windows"
		]
	},
	"sorting": 3,
	"layout": {
		"layout": "side",
		"aggregateFunction": "average",
		"showID": false,
		"showName": true,
		"showAggregateScores": false,
		"countUnscored": false
	},
	"hideDisabled": false,
	"techniques": [
		
	],
	"gradient": {
		"colors": [
			"#ff6666ff",
			"#ffe766ff",
			"#8ec843ff"
		],
		"minValue": 0,
		"maxValue": 100
	},
	"legendItems": [],
	"metadata": [],
	"links": [],
	"showTacticRowBackground": false,
	"tacticRowBackground": "#dddddd",
	"selectTechniquesAcrossTactics": false,
	"selectSubtechniquesWithParent": false
}
	return template_MITRE_small

techniques_template = {
			"techniqueID": "T1140",
			"tactic": "defense-evasion",
			"color": "#e60d0d",
			"comment": "",
			"enabled": true,
			"metadata": [],
			"links": [],
			"showSubtechniques": false
		}

class Malware_vector_info:
    def __init__(self, name = "", mitre_level2_vector= []):
        self.name = name
        self.mitre_level2_vector = mitre_level2_vector

path_data = "D:/LEARN/LEARN/DATN/02_resources/mitre_data_new/converted_data/"
save_path = "D:/LEARN/LEARN/DATN/02_resources/visualize/MITRE_json/"
with open(path_data + '01_malware_to_vectorlv2_listtype.pkl', 'rb') as f:
    list_malware_vector = pickle.load(f)

for malware_vector in list_malware_vector[0:1]:
	print(malware_vector)
	get_template = get_template_MITRE_full()
	print(f"name : {malware_vector[0]}")
	level2 = []

	print(f"before + {len(get_template['techniques'])}")
	for i,value in enumerate(malware_vector[1]):
		if value == 1:
			techni = MITRE_LEVEL2_VECTOR[i]
			level2.append(techni)
			print(techni)
			for tactic in dict_level2_to_level1[techni]:
				techniques_template["tactic"] = tactic
				techniques_template["techniqueID"] = dict_level2_to_id[techni]
				print(techniques_template)
				get_template['techniques'].append(techniques_template.copy())
	with open(f"{save_path}{malware_vector[0]}_MITRE_visualize.json", 'w') as fp:
		ujson.dump(get_template, fp)
	#print(len(level2))
	#print(level2)
	print(f"after + {len(get_template['techniques'])}")
	#print(malware_vector[2])

    # +++++++++++++ SMALL ++++++++++++++++
	print(malware_vector)
	get_template = get_template_MITRE_small()
	print(f"name : {malware_vector[0]}")
	level2 = []

	print(f"before + {len(get_template['techniques'])}")
	for i,value in enumerate(malware_vector[1]):
		if value == 1:
			techni = MITRE_LEVEL2_VECTOR[i]
			level2.append(techni)
			print(techni)
			for tactic in dict_level2_to_level1[techni]:
				techniques_template["tactic"] = tactic
				techniques_template["techniqueID"] = dict_level2_to_id[techni]
				print(techniques_template)
				get_template['techniques'].append(techniques_template.copy())
	with open(f"{save_path}{malware_vector[0]}_MITRE_visualize_small.json", 'w') as fp:
		ujson.dump(get_template, fp)
	#print(len(level2))
	#print(level2)
	print(f"after + {len(get_template['techniques'])}")